name: Auto-Merge Validated Packages

on:
  pull_request_target:
    types: [labeled]
    branches:
      - packages
    paths:
      - '*/hatch_metadata.json'

jobs:
  auto-merge:
    if: github.event.label.name == 'reviewed' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.HATCH_WORKFLOW_APP_ID }}
          private_key: ${{ secrets.HATCH_WORKFLOW_APP_PRIVATE_KEY }}
          
      - name: Auto-approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          
      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          MERGE_METHOD: squash
          MERGE_LABELS: validation-passed, reviewed